public class FibonacciSeries {

    public static void main(String[] args){
        long firstNumber= 0;
        long secondNumber = 1;
        long limit = 4000000;
        long sum = 2;
        long evenSum = 2;

        /**
         * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
         *
         * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
         *
         * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
         *
         */

        while(sum <= limit) {
            firstNumber = secondNumber;
            secondNumber = sum;
            sum = firstNumber + secondNumber;
            System.out.println("firstNumber = " + firstNumber + " secondNumber = " + secondNumber+ " sum = " + sum);
            if(sum % 2 == 0){
                evenSum = evenSum + sum;
                System.out.println("Even Sum = " + evenSum);
            }
        }
    }
}
